-- ! DROP
-- DROP TABLE ORD;
-- DROP TABLE LORD;
-- DROP TABLE ORD050414;
-- DROP TABLE COM;
-- DROP TABLE RANK;
-- DROP TABLE SALES;
-- DROP TABLE SALES2;
-- DROP TABLE DEPT;
-- DROP TABLE DEPT2;
-- DROP TABLE P66;
-- DROP TABLE Shohin;
-- ! CREATE
CREATE TABLE
  DEPT (
    DNO INTEGER CONSTRAINT PK_DEPT PRIMARY KEY,
    DNAME VARCHAR(15),
    LOC VARCHAR(10)
  );

CREATE TABLE
  SALES (
    SNO INTEGER CONSTRAINT PK_SALES PRIMARY KEY,
    SNAME VARCHAR(10),
    DNO INTEGER CONSTRAINT FK_DNO REFERENCES DEPT (DNO),
    MGR INTEGER,
    AMT INTEGER,
    EDATE DATE
  );

CREATE TABLE
  RANK(
    RNO VARCHAR(2) CONSTRAINT PK_RANK PRIMARY KEY,
    LAMT INTEGER,
    HAMT INTEGER
  );

CREATE TABLE
  COM (
    CNO INTEGER CONSTRAINT PK_COM PRIMARY KEY,
    CNAME VARCHAR(15),
    PRC INTEGER,
    SNO INTEGER CONSTRAINT FK_SNO REFERENCES SALES (SNO)
  );

CREATE TABLE
  ORD (
    ONO INTEGER CONSTRAINT PK_ORD PRIMARY KEY,
    CNO INTEGER CONSTRAINT FK_CNO REFERENCES COM (CNO),
    STD VARCHAR(1),
    QTY INTEGER,
    PRC INTEGER,
    ODATE DATE
  );

CREATE TABLE
  LORD (
    ONO INTEGER CONSTRAINT PK_LORD PRIMARY KEY,
    CNO INTEGER,
    STD VARCHAR(1),
    QTY INTEGER,
    PRC INTEGER,
    ODATE DATE
  );

CREATE TABLE
  ORD050414 (
    ONO INTEGER CONSTRAINT PK_ORD050414 PRIMARY KEY,
    CNO INTEGER,
    STD VARCHAR(1),
    QTY INTEGER,
    PRC INTEGER,
    ODATE DATE
  );

CREATE TABLE
  P66 (addr1 VARCHAR(20), addr2 CHAR(20));

CREATE TABLE
  DEPT2 (
    DNO INTEGER CONSTRAINT PK_DEPT2 PRIMARY KEY,
    DNAME VARCHAR(15),
    LOC VARCHAR(10)
  );

CREATE TABLE
  SALES2 (
    SNO INTEGER CONSTRAINT PK_SALES2 PRIMARY KEY,
    SNAME VARCHAR(10),
    DNO INTEGER CONSTRAINT FK_DNO2 REFERENCES DEPT (DNO),
    MGR INTEGER,
    AMT INTEGER,
    EDATE DATE
  );

CREATE TABLE
  Shohin (
    shohin_id CHAR(4) NOT NULL,
    shohin_mei VARCHAR(100) NOT NULL,
    shohin_bunrui VARCHAR(32) NOT NULL,
    hanbai_tanka INTEGER,
    shiire_tanka INTEGER,
    torokubi DATE,
    PRIMARY KEY (shohin_id)
  );

CREATE TABLE
  SampleLike (strcol VARCHAR(6) NOT NULL, PRIMARY KEY (strcol));

CREATE TABLE
  TenpoShohin (
    tenpo_id CHAR(4) NOT NULL,
    tenpo_mei VARCHAR(200) NOT NULL,
    shohin_id CHAR(4) NOT NULL,
    suryo INTEGER NOT NULL,
    PRIMARY KEY (tenpo_id, shohin_id)
  );

CREATE TABLE
  Shohin2 (
    shohin_id CHAR(4) NOT NULL,
    shohin_mei VARCHAR(100) NOT NULL,
    shohin_bunrui VARCHAR(32) NOT NULL,
    hanbai_tanka INTEGER,
    shiire_tanka INTEGER,
    torokubi DATE,
    PRIMARY KEY (shohin_id)
  );

CREATE TABLE
  GRADE (
    GNO VARCHAR(2) CONSTRAINT PK_GRADE PRIMARY KEY,
    LOW INTEGER,
    HIGH INTEGER
  );

CREATE TABLE
  ZaikoShohin (
    souko_id CHAR(4) NOT NULL,
    shohin_id CHAR(4) NOT NULL,
    zaiko_suryo INTEGER NOT NULL,
    PRIMARY KEY (souko_id, shohin_id)
  );

CREATE TABLE
  ShohinIns (
    shohin_id CHAR(4) NOT NULL,
    shohin_mei VARCHAR(100) NOT NULL,
    shohin_bunrui VARCHAR(32) NOT NULL,
    hanbai_tanka INTEGER DEFAULT 0,
    shiire_tanka INTEGER,
    torokubi DATE,
    PRIMARY KEY (shohin_id)
  );

CREATE TABLE
  ShohinCopy (
    shohin_id CHAR(4) NOT NULL,
    shohin_mei VARCHAR(100) NOT NULL,
    shohin_bunrui VARCHAR(32) NOT NULL,
    hanbai_tanka INTEGER,
    shiire_tanka INTEGER,
    torokubi DATE,
    PRIMARY KEY (shohin_id)
  );
